# Generated by Django 3.2.1 on 2022-01-11 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20220111_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 2, 46, 15, 874826, tzinfo=utc)),
        ),
    ]
